export default {
  '00': [
    '             ppp              ',
    '             ppp     fffffff  ',
    '             ppp     fffffff  ',
    '             ppp     fffffff  ',
    '             ppp     fffffff  ',
    '             ppp     fffffff  ',
    '             ppp     fffffff  ',
    '             ppp     fffffff  ',
    '             ppp     fffffff  ',
    '             ppp              ',
    '             ppppppppppppppppp',
    '             ppppppppppppppppp',
    '             ppppppppppppppppp',
    '                              ',
    '                              ',
    '                              ',
    '                              ',
    '                              ',
    '                              ',
  ],
  '01': [
    '                              ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                              ',
    'pppppppppppppppppppppppppp    ',
    'pppppppppppppppppppppppppp    ',
    'pppppppppppppppppppppppppp    ',
    '     fffff             ppp    ',
    '     fffff             ppppppp',
    '     fffff             ppppppp',
    '     fffff             ppppppp',
    '                              ',
    '                              ',
  ],
  '02': [
    '                              ',
    '  ffffffffffffffffffffffffff  ',
    '  ffffffffffffffffffffffffff  ',
    '  ffffffffffffffffffffffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                     fffffff  ',
    '                              ',
    '     fffff                    ',
    '     fffff                    ',
    '     fffff                    ',
    '     fffff                    ',
    'pppppppppppppppppppppppppppppp',
    'pppppppppppppppppppppppppppppp',
    'pppppppppppppppppppppppppppppp',
    '                              ',
    '                              ',
  ]
}