export default {
  '00': {
    map: [
      '                              ',
      '            opp[              ',
      '            opp[              ',
      '            opp[              ',
      '            opp[              ',
      '            opp[zxcxcv  zxcxcv',
      '            opp[              ',
      '            oppL0000000000000-',
      '            opppppppppppppppp[',
      '            opppppppppppppppp[',
      '            opp(;;;;;;;;;;_pp[',
      '            opp[1222222223opp[',
      '            opp[qwwwwwwwweopp[',
      '            opp[qwwwwwwwweopp[',
      '            opp[assssssssdopp[',
      '            oppL0000000000:pp[',
      '            opppppppppppppppp[',
      '            opppppppppppppppp[',
      '            l;;;;;;;;;;;;;;;;"',
      '                              ',
    ],
    pos: [100, 100]
  },
  '01': {
    map: [
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      'pppppppppppppppppppppppppp    ',
      'pppppppppppppppppppppppppp    ',
      'pppppppppppppppppppppppppp    ',
      '                       ppp    ',
      '                       ppppppp',
      '                       ppppppp',
      '                       ppppppp',
      '                              ',
      '                              ',
    ],
  },
  '02': { 
    map: [
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      '                              ',
      'pppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppp',
      '                              ',
      '                              ',
    ]
  }
}